import * as THREE from 'three'
import { COSMIC_QUALITY, normalizeCosmicWorld3000Config } from './CosmicWorld3000Config.js'

const TAU = Math.PI * 2
function rngFactory(seed=3000){let s=seed>>>0;return()=>((s=Math.imul(s,1664525)+1013904223>>>0)/4294967296)}
function mesh(g,m,name,x=0,y=0,z=0){const v=new THREE.Mesh(g,m);v.name=name;v.position.set(x,y,z);return v}
function mat(color,options={}){return new THREE.MeshStandardMaterial({color,roughness:.78,metalness:.12,flatShading:true,...options})}
function setInstance(target,i,x,y,z,scale=1,ry=0){const h=new THREE.Object3D();h.position.set(x,y,z);h.scale.setScalar(scale);h.rotation.y=ry;h.updateMatrix();target.setMatrixAt(i,h.matrix)}

function createPlatform(config,profile,colliders){
  const root=new THREE.Group();root.name='platform';const platformMat=mat(config.colors.platform,{emissive:'#090c35',emissiveIntensity:.5})
  const plaza=mesh(new THREE.CylinderGeometry(10,10.8,.55,16),platformMat,'centralPlaza',0,-.78,0);plaza.receiveShadow=true;root.add(plaza)
  const pathDefs=[['northPath',0,-20,config.pathWidth,30,0],['eastPath',20,0,30,config.pathWidth,0],['southPath',0,20,config.pathWidth,30,0],['westPath',-20,0,30,config.pathWidth,0]]
  const paths=new THREE.Group();paths.name='radiantPaths';for(const[name,x,z,w,d]of pathDefs){const p=mesh(new THREE.BoxGeometry(w,.42,d),platformMat,name,x,-.72,z);p.receiveShadow=true;paths.add(p)}root.add(paths)
  const ring=mesh(new THREE.RingGeometry(25,29,48),platformMat,'ringWalkway');ring.rotation.x=-Math.PI/2;ring.position.y=-.49;root.add(ring)
  const edgeMat=new THREE.MeshBasicMaterial({color:config.colors.cyan,transparent:true,opacity:.72})
  const guides=new THREE.Group();guides.name='pathEdgeLights';for(const z of[-35,35])guides.add(mesh(new THREE.BoxGeometry(7,.08,.18),edgeMat,'pathGuide',0,-.45,z));for(const x of[-35,35])guides.add(mesh(new THREE.BoxGeometry(.18,.08,7),edgeMat,'pathGuide',x,-.45,0));root.add(guides)
  const platforms=new THREE.Group();platforms.name='viewPlatforms';for(const[x,z,name]of[[0,-35,'planetViewPlatform'],[35,0,'moonViewPlatform'],[0,35,'rocketDockPlatform'],[-35,0,'cometViewPlatform']])platforms.add(mesh(new THREE.CylinderGeometry(7,7.5,.5,12),platformMat,name,x,-.74,z));root.add(platforms)
  const ramps=new THREE.Group();ramps.name='ramps';root.add(ramps)
  const barriers=new THREE.Group();barriers.name='energyBarriers';if(config.energyBarrierEnabled){const barrierMat=new THREE.MeshBasicMaterial({color:config.colors.cyan,transparent:true,opacity:.18,side:THREE.DoubleSide,depthWrite:false});const wall=mesh(new THREE.CylinderGeometry(config.playableRadius,config.playableRadius,1.6,64,1,true),barrierMat,'outerEnergyField',0,.28,0);barriers.add(wall);const rail=mesh(new THREE.TorusGeometry(config.playableRadius,.12,6,64),edgeMat,'visibleBoundaryRail',0,.18,0);rail.rotation.x=Math.PI/2;barriers.add(rail)}root.add(barriers)
  const underside=new THREE.Group();underside.name='undersideModules';for(let i=0;i<profile.platformDetails;i++){const a=i/profile.platformDetails*TAU,r=9+(i%3)*8;underside.add(mesh(new THREE.BoxGeometry(.7,.8,1.4),mat(i%2?'#283277':'#25204f',{emissive:i%2?'#156b8a':'#561359',emissiveIntensity:.5}),'orbitalModule',Math.cos(a)*r,-1.4,Math.sin(a)*r))}root.add(underside)
  return root
}

function addPlanetBands(planet,radius,colors){for(let i=0;i<colors.length;i++){const band=mesh(new THREE.TorusGeometry(radius*1.005,.08+radius*.018,5,32),new THREE.MeshBasicMaterial({color:colors[i]}),'planetColorBand');band.rotation.x=Math.PI/2;band.position.y=(i-(colors.length-1)/2)*radius*.36;planet.add(band)}}
function createCelestialBodies(config,profile,rng){
  const root=new THREE.Group();root.name='celestialBodies'
  const ringed=new THREE.Group();ringed.name='ringedPlanet';ringed.position.set(-24,16,-55);const planet=mesh(new THREE.IcosahedronGeometry(config.ringedPlanetScale,3),mat('#ff795c',{emissive:'#7a1939',emissiveIntensity:.32}),'ringedPlanetBody');ringed.add(planet);addPlanetBands(planet,config.ringedPlanetScale,['#ffb069','#ec496c','#ff7f67']);const planetRing=mesh(new THREE.RingGeometry(config.ringedPlanetScale*1.15,config.ringedPlanetScale*1.72,64),new THREE.MeshBasicMaterial({color:'#ffc3d4',transparent:true,opacity:.82,side:THREE.DoubleSide}),'planetRing');planetRing.rotation.x=1.15;planetRing.rotation.z=.22;ringed.add(planetRing);const atmosphere=mesh(new THREE.IcosahedronGeometry(config.ringedPlanetScale*1.08,2),new THREE.MeshBasicMaterial({color:'#ff7592',transparent:true,opacity:.08,side:THREE.BackSide}),'ringedAtmosphere');ringed.add(atmosphere);root.add(ringed)
  const home=new THREE.Group();home.name='cyanHomePlanet';home.position.set(8,-42,12);const homeBody=mesh(new THREE.IcosahedronGeometry(config.homePlanetScale,3),mat('#28dce2',{emissive:'#07599a',emissiveIntensity:.25}),'homePlanetBody');home.add(homeBody);addPlanetBands(homeBody,config.homePlanetScale,['#ffe66f','#39e6e4','#238ac9']);const homeGlow=mesh(new THREE.IcosahedronGeometry(config.homePlanetScale*1.04,2),new THREE.MeshBasicMaterial({color:'#4df4ff',transparent:true,opacity:.1,side:THREE.BackSide}),'homePlanetAtmosphere');home.add(homeGlow);root.add(home)
  const moon=new THREE.Group();moon.name='moon';moon.position.set(48,15,-17);const moonBody=mesh(new THREE.IcosahedronGeometry(9,2),mat('#777b88',{emissive:'#1c2032',emissiveIntensity:.18}),'moonBody');moon.add(moonBody);for(let i=0;i<8;i++){const a=rng()*TAU,b=(rng()-.5)*Math.PI,x=Math.cos(a)*Math.cos(b)*8.9,y=Math.sin(b)*8.9,z=Math.sin(a)*Math.cos(b)*8.9;const crater=mesh(new THREE.CircleGeometry(.7+rng()*1.3,8),new THREE.MeshBasicMaterial({color:i%2?'#505461':'#9296a0',side:THREE.DoubleSide}),'moonCrater',x,y,z);crater.lookAt(0,0,0);moonBody.add(crater)}root.add(moon)
  const asteroids=new THREE.InstancedMesh(new THREE.DodecahedronGeometry(1,0),mat('#666b78'),profile.asteroids);asteroids.name='asteroids';for(let i=0;i<profile.asteroids;i++){const a=i/profile.asteroids*TAU,r=13+rng()*9;setInstance(asteroids,i,48+Math.cos(a)*r,15+(rng()-.5)*9,-17+Math.sin(a)*r,.35+rng()*1.6,rng()*TAU)}asteroids.instanceMatrix.needsUpdate=true;root.add(asteroids)
  return{root,ringed,planet,planetRing,home,homeBody,moon,moonBody,asteroids}
}

function pointsLayer(name,count,rMin,rMax,colors,size,rng){const positions=[],colorValues=[],palette=colors.map(c=>new THREE.Color(c));for(let i=0;i<count;i++){const u=rng()*2-1,a=rng()*TAU,r=rMin+rng()*(rMax-rMin),s=Math.sqrt(1-u*u);positions.push(Math.cos(a)*s*r,u*r,Math.sin(a)*s*r);const c=palette[i%palette.length];colorValues.push(c.r,c.g,c.b)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('color',new THREE.Float32BufferAttribute(colorValues,3));const p=new THREE.Points(g,new THREE.PointsMaterial({size,vertexColors:true,transparent:true,opacity:.82,depthWrite:false,fog:false}));p.name=name;return p}
function createStars(profile,rng){const root=new THREE.Group();root.name='stars';const colors=['#ffffff','#fff2a6','#ffb5c5','#a9f6ff','#7adff0'];const far=pointsLayer('starsFar',profile.stars[0],78,110,colors,.25,rng),middle=pointsLayer('starsMiddle',profile.stars[1],52,77,colors,.34,rng),near=pointsLayer('starsNear',profile.stars[2],35,51,colors,.44,rng),dust=pointsLayer('spaceDust',Math.floor(profile.stars[1]*.35),24,60,['#7f8bd3','#b989c3'],.12,rng);root.add(far,middle,near,dust);return{root,layers:[far,middle,near,dust]}}

function createComet(profile){const root=new THREE.Group();root.name='comet';root.position.set(-54,28,18);const nucleus=mesh(new THREE.OctahedronGeometry(1.4,1),mat('#bffcff',{emissive:'#22dce5',emissiveIntensity:2}),'cometNucleus');root.add(nucleus);const tail=new THREE.InstancedMesh(new THREE.OctahedronGeometry(.28,0),new THREE.MeshBasicMaterial({color:'#43edf1',transparent:true,opacity:.65}),profile.cometTail);tail.name='cometTail';for(let i=0;i<profile.cometTail;i++)setInstance(tail,i,1.3+i*.28,(i%5-2)*.1,(i%7-3)*.08,Math.max(.1,1-i/profile.cometTail));tail.instanceMatrix.needsUpdate=true;root.add(tail);return root}
function createRocket(profile){const root=new THREE.Group();root.name='rocket';root.position.set(-38,13,45);root.rotation.z=-.55;root.add(mesh(new THREE.CylinderGeometry(.45,.6,2.8,8),mat('#ecedf6'),'rocketBody'),mesh(new THREE.ConeGeometry(.46,1.1,8),mat('#ef5367'),'rocketNose',0,1.92,0),mesh(new THREE.BoxGeometry(1.4,.55,.18),mat('#43bfe5'),'rocketFins',0,-1.05,0));const trail=new THREE.InstancedMesh(new THREE.OctahedronGeometry(.22,0),new THREE.MeshBasicMaterial({color:'#ffb42e',transparent:true,opacity:.8}),profile.rocketTrail);trail.name='rocketTrail';for(let i=0;i<profile.rocketTrail;i++)setInstance(trail,i,(i%3-1)*.08,-1.75-i*.25,(i%2-.5)*.08,Math.max(.12,1-i/profile.rocketTrail));trail.instanceMatrix.needsUpdate=true;root.add(trail);return root}
function createSpaceObjects(config,profile){const root=new THREE.Group();root.name='spaceObjects';const comet=createComet(profile);comet.visible=config.cometEnabled;const rocket=createRocket(profile);rocket.visible=config.rocketEnabled;root.add(comet,rocket);return{root,comet,rocket}}

function createLandmark(name,x,z,color,colliders){const root=new THREE.Group();root.name=name;root.position.set(x,0,z);const m=mat('#202553',{emissive:color,emissiveIntensity:.6});root.add(mesh(new THREE.CylinderGeometry(2.2,2.8,1.2,10),m,'stationBase',0,.1,0),mesh(new THREE.TorusGeometry(2.3,.14,6,24),new THREE.MeshBasicMaterial({color}),'stationHalo',0,2.1,0));root.children[1].rotation.x=Math.PI/2;colliders.push({x,z,radius:2.7,type:'landmark'});return root}
function createLandmarks(config,colliders){const root=new THREE.Group();root.name='landmarks';root.add(createLandmark('planetViewDeck',0,-35,config.colors.orange,colliders),createLandmark('moonObservatory',35,0,config.colors.cyan,colliders),createLandmark('rocketDock',0,35,config.colors.yellow,colliders),createLandmark('cometStation',-35,0,config.colors.pink,colliders));return root}
function createEffects(config,rng){const root=new THREE.Group();root.name='effects';const atmosphere=new THREE.Object3D();atmosphere.name='atmosphereGlow';root.add(atmosphere);const step=mesh(new THREE.RingGeometry(.45,.65,20),new THREE.MeshBasicMaterial({color:config.colors.cyan,transparent:true,opacity:0,side:THREE.DoubleSide,depthWrite:false}),'stepParticles');step.rotation.x=-Math.PI/2;step.position.y=-.46;root.add(step);const ripples=new THREE.Object3D();ripples.name='barrierRipples';root.add(ripples);const ambient=pointsLayer('ambientParticles',90,8,38,['#7eeeff','#ffb4d0'],.12,rng);root.add(ambient);return{root,step,ambient}}
function createLighting(config){const root=new THREE.Group();root.name='lighting';const ambient=new THREE.HemisphereLight('#7788d8','#090b29',1.45);ambient.name='ambientLight';root.add(ambient);const warm=new THREE.DirectionalLight('#ff9a68',1.45);warm.name='planetLight';warm.position.set(-20,18,-30);root.add(warm);const cyan=new THREE.PointLight('#48ecff',13,38,2);cyan.name='cyanRimLight';cyan.position.set(0,-3,7);root.add(cyan);const accent=new THREE.PointLight('#ffcb72',7,34,2);accent.name='warmAccentLight';accent.position.set(-16,6,-15);root.add(accent);return{root,cyan,accent}}

export function createCosmicWorld3000(overrides={}){
  const config=normalizeCosmicWorld3000Config(overrides),profile=COSMIC_QUALITY[config.quality],rng=rngFactory(),colliders=[];const world=new THREE.Group();world.name='cosmicWorld3000';world.userData.targetTokenId='3000';world.userData.config=config
  const dome=mesh(new THREE.SphereGeometry(112,20,12),new THREE.MeshBasicMaterial({color:config.colors.space,side:THREE.BackSide,depthWrite:false,fog:false}),'deepSpaceDome');dome.name='deepSpaceDome'
  const platform=createPlatform(config,profile,colliders),celestial=createCelestialBodies(config,profile,rng),spaceObjects=createSpaceObjects(config,profile),stars=createStars(profile,rng),landmarks=createLandmarks(config,colliders),effects=createEffects(config,rng),lighting=createLighting(config)
  const navigation=new THREE.Group();navigation.name='navigation';for(const name of['spawnPoint','walkableAreas','worldBoundaries']){const o=new THREE.Object3D();o.name=name;navigation.add(o)}const debug=new THREE.Group();debug.name='colliders';debug.visible=config.debug.showColliders;navigation.add(debug)
  const modules={platform,celestialBodies:celestial.root,spaceObjects:spaceObjects.root,stars:stars.root,landmarks,effects:effects.root,lighting:lighting.root,navigation};world.add(dome,...Object.values(modules));world.visible=config.enabled
  let disposed=false,characterState=null,previous=0
  function sampleSurfaceHeight(){return-.5}function sampleCharacterGroundY(){return 0}
  function resolveMovement(current,proposed){const next=proposed.clone();let collided=false;const d=Math.hypot(next.x,next.z),max=config.playableRadius-.65;if(d>max){next.x*=max/d;next.z*=max/d;collided=true}if(config.collisionEnabled)for(const c of colliders){let dx=next.x-c.x,dz=next.z-c.z,distance=Math.hypot(dx,dz),minimum=c.radius+.44;if(distance<minimum){if(distance<.001){dx=1;dz=0;distance=1}next.x=c.x+dx/distance*minimum;next.z=c.z+dz/distance*minimum;collided=true}}next.y=0;return{position:next,collided}}
  function update(time){if(disposed)return;const dt=Math.min(Math.max(time-previous,0),.05);previous=time;celestial.planet.rotation.y=time*.025;celestial.planetRing.rotation.z=.22+time*.008;celestial.homeBody.rotation.y=-time*.008;celestial.moonBody.rotation.y=time*.012;celestial.asteroids.rotation.y=time*.016;stars.layers.forEach((layer,i)=>{layer.rotation.y=time*(.0004+i*.00025);if(config.starTwinkleEnabled)layer.material.opacity=(config.reducedFlashing?.66:.76)+Math.sin(time*(.35+i*.12)+i)*.08});spaceObjects.comet.position.x=-54+((time*2.4)%125);spaceObjects.comet.position.y=27+Math.sin(time*.18)*5;spaceObjects.rocket.position.x=-43+((time*1.15)%105);spaceObjects.rocket.position.z=45-((time*.85)%90);spaceObjects.comet.children[0].rotation.y+=dt*.5;effects.ambient.rotation.y=time*.006;if(characterState&&config.stepParticlesEnabled){effects.step.position.x=characterState.position?.x||0;effects.step.position.z=characterState.position?.z||0;effects.step.material.opacity=characterState.moving?.2+Math.sin(time*7)*.05:0;effects.step.scale.setScalar(1+(time%1)*.25)}}
  function dispose(){if(disposed)return;disposed=true;world.traverse(o=>{o.geometry?.dispose?.();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose?.());else o.material?.dispose?.()});world.removeFromParent()}
  const runtime=Object.freeze({config,world,modules:Object.freeze(modules),colliders,sampleSurfaceHeight,sampleCharacterGroundY,resolveMovement,setCharacterState(v){characterState=v},update,setEnabled(v){world.visible=Boolean(v)},setModuleVisible(name,v){if(modules[name])modules[name].visible=Boolean(v)},setDebugColliders(v){debug.visible=Boolean(v)},dispose});Object.defineProperty(world,'environmentRuntime',{value:runtime});world.userData.update=t=>runtime.update(t);return runtime
}
