import * as THREE from 'three'
import { normalizeStormWorld11Config, STORM_QUALITY } from './StormWorld11Config.js'
const TAU = Math.PI * 2
function rngFactory(seed = 11) { let s = seed >>> 0; return () => ((s = Math.imul(s, 1664525) + 1013904223 >>> 0) / 4294967296) }
function mat(color, options = {}) { return new THREE.MeshStandardMaterial({ color, roughness: .88, metalness: 0, flatShading: true, ...options }) }
function mesh(g, m, name, x = 0, y = 0, z = 0) { const value = new THREE.Mesh(g, m); value.name = name; value.position.set(x, y, z); return value }
function setInstance(target, i, x, y, z, scale = 1, ry = 0) { const helper = new THREE.Object3D(); helper.position.set(x, y, z); helper.rotation.y = ry; helper.scale.setScalar(scale); helper.updateMatrix(); target.setMatrixAt(i, helper.matrix) }
function terrainSurface(x, z, config) { const distance = Math.hypot(x, z); const outer = THREE.MathUtils.smoothstep(distance, 12, config.playableRadius); return -.52 + outer * (Math.sin(x * .11) * .35 + Math.cos(z * .09) * .3) * config.terrainHeight * .5 }

function createTerrain(config, rng) {
  const root = new THREE.Group(); root.name = 'terrain'; const geometry = new THREE.PlaneGeometry(config.worldSize, config.worldSize, 38, 38); geometry.rotateX(-Math.PI / 2); const p = geometry.attributes.position
  for (let i = 0; i < p.count; i++) p.setY(i, terrainSurface(p.getX(i), p.getZ(i), config)); geometry.computeVertexNormals()
  const plateau = mesh(geometry, mat('#172d42', { roughness: .76 }), 'centralPlateau'); plateau.receiveShadow = true; root.add(plateau)
  const paths = new THREE.Group(); paths.name = 'rockyPaths'; const pathMat = mat('#263f55'); for (let dir = 0; dir < 4; dir++) for (let i = 0; i < 7; i++) { const a = dir * Math.PI / 2, stone = mesh(new THREE.BoxGeometry(4.2, .13, 3.2), pathMat, 'pathStone', Math.sin(a) * (6 + i * 4.2), -.43, Math.cos(a) * (6 + i * 4.2)); stone.rotation.y = a; paths.add(stone) } root.add(paths)
  const slopes = new THREE.Object3D(); slopes.name = 'slopes'; root.add(slopes)
  const bridges = new THREE.Group(); bridges.name = 'stoneBridges'; for (let i = 0; i < 8; i++) bridges.add(mesh(new THREE.BoxGeometry(3.5, .3, 1.5), pathMat, 'bridgeSlab', 18, -.25, -14 + i * 1.6)); root.add(bridges)
  const puddles = new THREE.Group(); puddles.name = 'puddles'; if (config.puddlesEnabled) for (let i = 0; i < 11; i++) { const water = mesh(new THREE.CircleGeometry(1.2 + rng() * 2.3, 18), new THREE.MeshStandardMaterial({ color: '#244e68', emissive: '#7fdcff', emissiveIntensity: .03, roughness: .12, transparent: true, opacity: .72 }), `puddle-${i}`, (rng() - .5) * 58, -.43, (rng() - .5) * 58); water.rotation.x = -Math.PI / 2; puddles.add(water) } root.add(puddles)
  const chasms = new THREE.Group(); chasms.name = 'chasms'; for (let i = 0; i < 4; i++) { const chasm = mesh(new THREE.BoxGeometry(5, .18, 16), new THREE.MeshBasicMaterial({ color: '#07121e' }), `chasm-${i}`, i < 2 ? -33 : 33, -.32, i % 2 ? 17 : -17); chasm.rotation.y = i * .42; chasms.add(chasm) } root.add(chasms)
  return { root, puddles }
}

function createLandmarks(config, rng, colliders) {
  const root = new THREE.Group(); root.name = 'landmarks'
  const peak = new THREE.Group(); peak.name = 'northernPeak'; peak.position.set(0, 5, -48); peak.add(mesh(new THREE.ConeGeometry(13, 24, 7, 3), mat('#16283a'), 'mainPeak')); root.add(peak)
  const pillars = new THREE.Group(); pillars.name = 'easternRockPillars'; for (let i = 0; i < 9; i++) { const x = 24 + i % 3 * 5, z = -15 + Math.floor(i / 3) * 11, rock = mesh(new THREE.CylinderGeometry(1.6, 2.4, 7 + i % 4 * 2, 6), mat('#26394a'), `pillar-${i}`, x, 2.5 + i % 4, z); pillars.add(rock); colliders.push({ x, z, radius: 2.3, type: 'pillar' }) } root.add(pillars)
  const plain = new THREE.Group(); plain.name = 'southernStormPlain'; for (let i = 0; i < 10; i++) plain.add(mesh(new THREE.DodecahedronGeometry(1.8 + rng() * 1.2, 0), mat('#24384a'), 'plainRock', -22 + i * 5, -.05, 30 + Math.sin(i) * 4)); root.add(plain)
  const ruins = new THREE.Group(); ruins.name = 'westernRuins'; for (let i = 0; i < 7; i++) { const x = -29 + i % 2 * 5, z = -18 + i * 6, ruin = mesh(new THREE.BoxGeometry(2.2, 6 - i % 3, 2.2), mat('#344755'), `ruin-${i}`, x, 1.8, z); ruin.rotation.z = (i % 2 ? 1 : -1) * .12; ruins.add(ruin); colliders.push({ x, z, radius: 1.8, type: 'ruin' }) } root.add(ruins)
  const tower = new THREE.Group(); tower.name = 'lightningTower'; tower.position.set(-22, 0, -28); tower.add(mesh(new THREE.CylinderGeometry(.45, 1.3, 13, 6), mat('#293945', { metalness: .25 }), 'towerMast', 0, 5.8, 0)); root.add(tower); colliders.push({ x: -22, z: -28, radius: 1.5, type: 'tower' })
  return root
}

function createAtmosphere(config, profile, rng) {
  const root = new THREE.Group(); root.name = 'atmosphere'; const sky = mesh(new THREE.SphereGeometry(config.worldSize * .7, 16, 9), new THREE.MeshBasicMaterial({ color: '#0b1c2b', side: THREE.BackSide, fog: false, depthWrite: false }), 'rainFog'); root.add(sky)
  function layer(name, count, y, color, radius) { const clouds = new THREE.InstancedMesh(new THREE.DodecahedronGeometry(2.4, 0), new THREE.MeshBasicMaterial({ color, transparent: true, opacity: .92, depthWrite: false }), count); clouds.name = name; for (let i = 0; i < count; i++) { const a = rng() * TAU, r = radius + rng() * 24; setInstance(clouds, i, Math.cos(a) * r, y + rng() * 5, Math.sin(a) * r, .7 + rng() * 1.6, rng() * TAU) } clouds.instanceMatrix.needsUpdate = true; root.add(clouds); return clouds }
  const total = profile.clouds, high = layer('highClouds', Math.floor(total * .3), 20, '#747d84', 24), middle = layer('middleClouds', Math.floor(total * .4), 14, '#46525c', 20), low = layer('lowClouds', Math.floor(total * .3), 9, '#263746', 18)
  const wall = mesh(new THREE.TorusGeometry(53, 10, 5, 48), new THREE.MeshBasicMaterial({ color: '#263440', transparent: true, opacity: .7 }), 'distantCloudWall', 0, 8, 0); wall.rotation.x = Math.PI / 2; root.add(wall)
  return { root, layers: [high, middle, low] }
}

function createRainLayer(name, count, radius, length, color, opacity, speed, config, rng) {
  const positions = new Float32Array(count * 6), velocities = new Float32Array(count), dx = Math.tan(THREE.MathUtils.degToRad(config.rainAngle)) * length
  for (let i = 0; i < count; i++) { const x = (rng() - .5) * radius * 2, y = rng() * 30, z = (rng() - .5) * radius * 2, o = i * 6; positions[o] = x; positions[o + 1] = y; positions[o + 2] = z; positions[o + 3] = x + dx; positions[o + 4] = y - length; positions[o + 5] = z; velocities[i] = speed * (.75 + rng() * .5) }
  const geometry = new THREE.BufferGeometry(); geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3)); const lines = new THREE.LineSegments(geometry, new THREE.LineBasicMaterial({ color, transparent: true, opacity, depthWrite: false })); lines.name = name; Object.defineProperty(lines, 'rainRuntime', { value: { velocities, radius, length, dx } }); return lines
}
function createWeather(config, profile, rng) { const root = new THREE.Group(); root.name = 'weather'; const layers = [createRainLayer('rainFar', Math.floor(profile.rain[0] * config.rainDensity), 55, .7, '#708da4', .35, 11, config, rng), createRainLayer('rainMiddle', Math.floor(profile.rain[1] * config.rainDensity), 38, 1.25, '#9fc8dd', .58, 16, config, rng), createRainLayer('rainNear', Math.floor(profile.rain[2] * config.rainDensity), 23, 2.1, '#e3f9ff', .82, 22, config, rng)]; root.add(...layers); const splashes = new THREE.Group(); splashes.name = 'groundSplashes'; root.add(splashes); const wind = new THREE.Object3D(); wind.name = 'windSystem'; root.add(wind); return { root, layers } }

function createLightning(config, rng) {
  const root = new THREE.Group(); root.name = 'lightning'; const bolts = new THREE.Group(); bolts.name = 'lightningBolts'; const material = new THREE.LineBasicMaterial({ color: '#c8f5ff', transparent: true, opacity: 0 })
  for (let b = 0; b < 5; b++) { const points = []; let x = -28 + b * 14, y = 25, z = -32 + (b % 3) * 28; points.push(new THREE.Vector3(x, y, z)); for (let i = 1; i < 9; i++) { x += (rng() - .5) * 5; y -= 3; z += (rng() - .5) * 2; points.push(new THREE.Vector3(x, y, z)) } const bolt = new THREE.Line(new THREE.BufferGeometry().setFromPoints(points), material.clone()); bolt.name = `bolt-${b}`; bolt.visible = false; bolts.add(bolt) } root.add(bolts)
  const illumination = new THREE.PointLight('#9fe9ff', 0, 70, 1.4); illumination.name = 'cloudIllumination'; illumination.position.set(0, 16, 0); root.add(illumination); const light = new THREE.DirectionalLight('#d8f8ff', 0); light.name = 'lightningLight'; light.position.set(0, 18, 5); root.add(light); const reflection = new THREE.Object3D(); reflection.name = 'reflectionFlash'; root.add(reflection)
  return { root, bolts, illumination, light }
}

function createDecorations(profile, rng, colliders) { const root = new THREE.Group(); root.name = 'decorations'; const deadTrees = new THREE.Group(); deadTrees.name = 'deadTrees'; for (let i = 0; i < 8; i++) { const x = -18 + i * 5, z = i % 2 ? 25 : -24; const trunk = mesh(new THREE.CylinderGeometry(.18, .42, 4.5, 5), mat('#18232b'), `deadTree-${i}`, x, 1.3, z); trunk.rotation.z = (rng() - .5) * .3; deadTrees.add(trunk) } root.add(deadTrees)
  const rocks = new THREE.InstancedMesh(new THREE.DodecahedronGeometry(.8, 0), mat('#334858'), profile.rocks); rocks.name = 'rocks'; for (let i = 0; i < profile.rocks; i++) { const a = rng() * TAU, r = 17 + rng() * 22; setInstance(rocks, i, Math.cos(a) * r, -.05, Math.sin(a) * r, .5 + rng() * 1.4, rng() * TAU) } rocks.instanceMatrix.needsUpdate = true; root.add(rocks)
  const crystals = new THREE.Group(); crystals.name = 'glowingCrystals'; for (let i = 0; i < 12; i++) crystals.add(mesh(new THREE.OctahedronGeometry(.55 + i % 3 * .18, 0), mat('#66d9ff', { emissive: '#2aaed8', emissiveIntensity: .7 }), `crystal-${i}`, 20 + i % 4 * 3, .2, -15 + Math.floor(i / 4) * 9)); root.add(crystals); const ruins = new THREE.Object3D(); ruins.name = 'ruinedStructures'; root.add(ruins); return root }

export function createStormWorld11(overrides = {}) {
  const config = normalizeStormWorld11Config(overrides), profile = STORM_QUALITY[config.quality], rng = rngFactory(), colliders = []; const world = new THREE.Group(); world.name = 'stormWorld11'; world.userData.targetTokenId = '11'; world.userData.config = config
  const terrain = createTerrain(config, rng), landmarks = createLandmarks(config, rng, colliders), atmosphere = createAtmosphere(config, profile, rng), weather = createWeather(config, profile, rng), lightning = createLightning(config, rng), decorations = createDecorations(profile, rng, colliders)
  const navigation = new THREE.Group(); navigation.name = 'navigation'; const spawn = new THREE.Object3D(); spawn.name = 'spawnPoint'; navigation.add(spawn); const walkable = new THREE.Object3D(); walkable.name = 'walkableAreas'; navigation.add(walkable); const debug = new THREE.Group(); debug.name = 'colliders'; debug.visible = config.debug.showColliders; navigation.add(debug); const boundary = new THREE.Object3D(); boundary.name = 'worldBoundaries'; navigation.add(boundary)
  world.add(terrain.root, landmarks, atmosphere.root, weather.root, lightning.root, decorations, navigation); world.visible = config.enabled
  let previous = 0, nextStrike = 2.5, flashEnd = 0, activeBolt = 0, disposed = false, characterState = null
  function sampleSurfaceHeight(x, z) { return terrainSurface(x, z, config) } function sampleCharacterGroundY(x, z) { return sampleSurfaceHeight(x, z) + .52 }
  function resolveMovement(current, proposed) { const next = proposed.clone(); let collided = false; const d = Math.hypot(next.x, next.z), max = config.playableRadius - .7; if (d > max) { next.x *= max / d; next.z *= max / d; collided = true } if (config.collisionEnabled) for (const c of colliders) { let dx = next.x - c.x, dz = next.z - c.z, distance = Math.hypot(dx, dz), min = c.radius + .42; if (distance < min) { if (distance < .001) { dx = 1; dz = 0; distance = 1 } next.x = c.x + dx / distance * min; next.z = c.z + dz / distance * min; collided = true } } next.y = sampleCharacterGroundY(next.x, next.z); return { position: next, collided } }
  function update(time) { if (disposed) return; const dt = Math.min(Math.max(time - previous, 0), .05); previous = time; weather.layers.forEach((layer, li) => { const p = layer.geometry.attributes.position, rt = layer.rainRuntime; for (let i = 0; i < rt.velocities.length; i++) { const o = i * 6, fall = rt.velocities[i] * config.rainSpeed * dt, drift = config.windStrength * dt * (1 + li * .3); p.array[o + 1] -= fall; p.array[o + 4] -= fall; p.array[o] += drift; p.array[o + 3] += drift; if (p.array[o + 4] < -.5) { p.array[o + 1] += 30; p.array[o + 4] += 30 } } p.needsUpdate = true }); atmosphere.layers.forEach((layer, i) => { layer.rotation.y = time * (.0015 + i * .0008) }); if (config.lightningEnabled && time > nextStrike) { lightning.bolts.children.forEach(b => { b.visible = false }); activeBolt = (activeBolt + 1) % lightning.bolts.children.length; lightning.bolts.children[activeBolt].visible = true; lightning.bolts.children[activeBolt].material.opacity = config.reducedFlashing ? .55 : .95; flashEnd = time + (config.reducedFlashing ? .09 : .16); nextStrike = time + 2.4 + rng() * (5.5 / Math.max(config.lightningFrequency, .1)) } const flashing = time < flashEnd; const strength = flashing ? config.lightningBrightness * (config.reducedFlashing ? .35 : 1) : 0; lightning.illumination.intensity = strength * 7; lightning.light.intensity = strength * 3; if (!flashing) lightning.bolts.children.forEach(b => { b.visible = false }); terrain.puddles.children.forEach(p => { p.material.emissiveIntensity = .03 + strength * .45 }) }
  function dispose() { if (disposed) return; disposed = true; world.traverse(o => { o.geometry?.dispose?.(); if (Array.isArray(o.material)) o.material.forEach(m => m.dispose?.()); else o.material?.dispose?.() }); world.removeFromParent() }
  const modules = Object.freeze({ terrain: terrain.root, landmarks, atmosphere: atmosphere.root, weather: weather.root, lightning: lightning.root, decorations, navigation }); const runtime = Object.freeze({ config, world, modules, colliders, sampleSurfaceHeight, sampleCharacterGroundY, resolveMovement, setCharacterState(v) { characterState = v }, update, setEnabled(v) { world.visible = Boolean(v) }, setModuleVisible(n, v) { if (modules[n]) modules[n].visible = Boolean(v) }, setDebugColliders(v) { debug.visible = Boolean(v) }, dispose }); Object.defineProperty(world, 'environmentRuntime', { value: runtime }); world.userData.update = t => runtime.update(t, characterState); return runtime
}
